# Kafka https://kafka.apache.org/quickstart

version: "3.7"
services:
    zookeeper:
        restart: always
        hostname: zookeeper
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            nat-network:
                ipv4_address: 10.0.100.2
        #logging:
        #    driver: "none"

    kafka:
        restart: always
        image: wurstmeister/kafka
        ports:
          - "9092:9092"
        hostname: kafka
        environment:
            #DOCKER_API_VERSION: 1.22
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
            nat-network:
                ipv4_address: 10.0.100.3
        #logging:
        #    driver: "none"
        depends_on:
        - zookeeper

    rr-tool:
        restart: always
        build: rr-tool
        hostname: rr-tool
        stdin_open: true
        tty: true
        networks:
            # eth0
            nat-network:
                ipv4_address: 10.0.100.5
        depends_on:
            - kafka
        environment:
            #KAFKA_IP: "10.101.41.255"
            KAFKA_IP: "10.0.100.3"
            KAFKA_PORT: "9092"
            TOPIC_TI_NETFLOW: "ti.threat_findings_netflow"
            TOPIC_TI_SYSLOG: "ti.threat_findings_syslog"
            TOPIC_RR_PROACTIVE_REMEDIATION: "rr.proactive_remediation"
            TOPIC_RR_NEW_ATTACK_REMEDIATION: "rr.new_attack_remedation"
            TOPIC_PORTAL_NOTIFICATIONS: "actions-notifications"
            TOPIC_IR_INCIDENT_DETECTED: "ir.detected_incident"
            RR_TOOL_IP: "10.?.?.?"
            SC_ORCHESTRATOR_IP: "10.101.41.168"
            SC_CLUSTER_PORT: "50101"
            IPTABLES_SC_ID: "dfbba196-c6b9-406c-9853-6eabfd865794"
            IGRAPH_PICTURES_OUTPUT_FOLDER: ""

networks:
    nat-network:
        internal: false
        name: nat-network
        ipam:
            config:
                - subnet: "10.0.100.0/24"
