apiVersion: v1
kind: Pod
metadata:
  name: rr-tool
spec:
  restartPolicy: OnFailure
  containers:
    - name: palantir-rr-tool
      image: 10.101.10.244:5000/palantir-rr-tool:1.0
      imagePullPolicy: Always
      env:
        - name: RR_INSTANCE_IDENTIFIER
          value: "0001"
        - name: RR_TOOL_MODE # standalone/kafka
          value: "kafka"
        - name: KAFKA_IP
          value: "10.101.41.255"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_POLLING_TIMEOUT
          value: "1.0"
        - name: TOPIC_TI_NETFLOW
          value: "ti.threat_findings_netflow"
        - name: TOPIC_TI_SYSLOG
          value: "ti.threat_findings_syslog"
        - name: TOPIC_RR_PROACTIVE_REMEDIATION
          value: "rr.proactive_remediation"
        - name: TOPIC_RR_NEW_ATTACK_REMEDIATION
          value: "rr.new_attack_remedation"
        - name: TOPIC_PORTAL_NOTIFICATIONS
          value: "actions-notifications"
        - name: TOPIC_IR_INCIDENT_DETECTED
          value: "ir.detected_incident"
        - name: RR_TOOL_IP
          value: "10.101.41.42"
        - name: SC_ORCHESTRATOR_IP
          value: "10.101.41.168"
        - name: ENABLE_MANO_API
          value: "1"
        - name: ENABLE_ONLY_SECURITY_CAPABILITIES_WITH_TRANSLATOR
          value: "1"
        - name: RESET_SECURITY_CONTROLS_RULES_AT_STARTUP
          value: "1"
        - name: ENABLE_IDENTICAL_L4_FILTERING_RULE_SKIPPING
          value: "1"
        - name: ENABLE_DEFAULT_L4_FILTERING_RULE_PROTOCOL
          value: "0"
        - name: ENABLE_DEFAULT_L4_FILTERING_RULE_ATTACKER_PORT
          value: "0"
        - name: ENABLE_DEFAULT_L4_FILTERING_RULE_VICTIM_PORT
          value: "0"
        - name: ENABLE_DEFAULT_L4_FILTERING_RULE_VICTIM_IP
          value: "1"
        - name: SC_CLUSTER_PORT
          value: "50101"
        - name: TI_SYSLOG_VICTIM_IP_FIELD_NAME
          value: "Source_IP"
        - name: BACKUP_SERVER_IP
          value: "10.225.1.73"
        - name: IGRAPH_PICTURES_OUTPUT_FOLDER
          value: ""
